INSERT INTO cat (breed, code) VALUES ('Abyssinian', 'abys')
INSERT INTO cat (breed, code) VALUES ('Aegean', 'aege')
INSERT INTO cat (breed, code) VALUES ('American Bobtail', 'abob')
INSERT INTO cat (breed, code) VALUES ('American Curl', 'acur')
INSERT INTO cat (breed, code) VALUES ('American Shorthair', 'ahso')
INSERT INTO cat (breed, code) VALUES ('American Wirehair', 'awir')
INSERT INTO cat (breed, code) VALUES ('Arabian Mau', 'amau')
INSERT INTO cat (breed, code) VALUES ('Australian Mist', 'amis')
INSERT INTO cat (breed, code) VALUES ('Balinese', 'bali')
INSERT INTO cat (breed, code) VALUES ('Bambino', 'bamb')
INSERT INTO cat (breed, code) VALUES ('Bengal', 'beng')
INSERT INTO cat (breed, code) VALUES ('Birman', 'birm')
INSERT INTO cat (breed, code) VALUES ('Bombay', 'bomb')
INSERT INTO cat (breed, code) VALUES ('British Longhair', 'bslo')
INSERT INTO cat (breed, code) VALUES ('British Shorthair', 'bsho')
INSERT INTO cat (breed, code) VALUES ('Burmese', 'bure')
INSERT INTO cat (breed, code) VALUES ('Burmilla', 'buri')
INSERT INTO cat (breed, code) VALUES ('California Spangled', 'cspa')
INSERT INTO cat (breed, code) VALUES ('Chantilly-Tiffany', 'ctif')
INSERT INTO cat (breed, code) VALUES ('Chausie', 'chau')
INSERT INTO cat (breed, code) VALUES ('Cheetoh', 'chee')
INSERT INTO cat (breed, code) VALUES ('Colorpoint Shorthair', 'csho')
INSERT INTO cat (breed, code) VALUES ('Cornish Rex', 'crex')
INSERT INTO cat (breed, code) VALUES ('Cymric', 'cymr')
INSERT INTO cat (breed, code) VALUES ('Cyprus', 'cypr')
INSERT INTO cat (breed, code) VALUES ('Devon Rex', 'drex')
INSERT INTO cat (breed, code) VALUES ('Donskoy', 'dons')
INSERT INTO cat (breed, code) VALUES ('Dragon Li', 'lihu')
INSERT INTO cat (breed, code) VALUES ('Egyptian Mau', 'emau')
INSERT INTO cat (breed, code) VALUES ('European Burmese', 'ebur')
INSERT INTO cat (breed, code) VALUES ('Exotic Shorthair', 'esho')
INSERT INTO cat (breed, code) VALUES ('Havana Brown', 'hbro')
INSERT INTO cat (breed, code) VALUES ('Himalayan', 'hima')
INSERT INTO cat (breed, code) VALUES ('Japanese Bobtail', 'jbob')
INSERT INTO cat (breed, code) VALUES ('Javanese', 'java')
INSERT INTO cat (breed, code) VALUES ('Khao Manee', 'khao')
INSERT INTO cat (breed, code) VALUES ('Korat', 'kora')
INSERT INTO cat (breed, code) VALUES ('Kurilian', 'kuri')
INSERT INTO cat (breed, code) VALUES ('LaPerm', 'lape')
INSERT INTO cat (breed, code) VALUES ('Maine Coon', 'mcoo')
INSERT INTO cat (breed, code) VALUES ('Malayan', 'mala')
INSERT INTO cat (breed, code) VALUES ('Manx', 'manx')
INSERT INTO cat (breed, code) VALUES ('Munchkin', 'munc')
INSERT INTO cat (breed, code) VALUES ('Nebelung', 'nebe')
INSERT INTO cat (breed, code) VALUES ('Norwegian Forest Cat', 'norw')
INSERT INTO cat (breed, code) VALUES ('Ocicat', 'ocic')
INSERT INTO cat (breed, code) VALUES ('Oriental', 'orie')
INSERT INTO cat (breed, code) VALUES ('Persian', 'pers')
INSERT INTO cat (breed, code) VALUES ('Pixie-bob', 'pixi')
INSERT INTO cat (breed, code) VALUES ('Ragamuffin', 'raga')
INSERT INTO cat (breed, code) VALUES ('Ragdoll', 'ragd')
INSERT INTO cat (breed, code) VALUES ('Russian Blue', 'rblu')
INSERT INTO cat (breed, code) VALUES ('Savannah', 'sava')
INSERT INTO cat (breed, code) VALUES ('Scottish Fold', 'sfol')
INSERT INTO cat (breed, code) VALUES ('Selkirk Rex', 'srex')
INSERT INTO cat (breed, code) VALUES ('Siamese', 'siam')
INSERT INTO cat (breed, code) VALUES ('Siberian', 'sibe')
INSERT INTO cat (breed, code) VALUES ('Singapura', 'sing')
INSERT INTO cat (breed, code) VALUES ('Snowshoe', 'snow')
INSERT INTO cat (breed, code) VALUES ('Somali', 'soma')
INSERT INTO cat (breed, code) VALUES ('Sphynx', 'sphy')
INSERT INTO cat (breed, code) VALUES ('Tonkinese', 'tonk')
INSERT INTO cat (breed, code) VALUES ('Toyger', 'toyg')
INSERT INTO cat (breed, code) VALUES ('Turkish Angora', 'tang')
INSERT INTO cat (breed, code) VALUES ('Turkish Van', 'tvan')
INSERT INTO cat (breed, code) VALUES ('York Chocolate', 'ycho')

INSERT INTO dog (breed) VALUES ('Affenpinscher')
INSERT INTO dog (breed) VALUES ('African')
INSERT INTO dog (breed) VALUES ('Airedale')
INSERT INTO dog (breed) VALUES ('Akita')
INSERT INTO dog (breed) VALUES ('Appenzeller')
INSERT INTO dog (breed) VALUES ('Shepherd Australian')
INSERT INTO dog (breed) VALUES ('Basenji')
INSERT INTO dog (breed) VALUES ('Beagle')
INSERT INTO dog (breed) VALUES ('Bluetick')
INSERT INTO dog (breed) VALUES ('Borzoi')
INSERT INTO dog (breed) VALUES ('Bouvier')
INSERT INTO dog (breed) VALUES ('Boxer')
INSERT INTO dog (breed) VALUES ('Brabancon')
INSERT INTO dog (breed) VALUES ('Briard')
INSERT INTO dog (breed) VALUES ('Norwegian Buhund')
INSERT INTO dog (breed) VALUES ('Boston Bulldog')
INSERT INTO dog (breed) VALUES ('English Bulldog')
INSERT INTO dog (breed) VALUES ('French Bulldog')
INSERT INTO dog (breed) VALUES ('Staffordshire Bullterrier')
INSERT INTO dog (breed) VALUES ('Australian Cattledog')
INSERT INTO dog (breed) VALUES ('Chihuahua')
INSERT INTO dog (breed) VALUES ('Chow')
INSERT INTO dog (breed) VALUES ('Clumber')
INSERT INTO dog (breed) VALUES ('Cockapoo')
INSERT INTO dog (breed) VALUES ('Border Collie')
INSERT INTO dog (breed) VALUES ('Coonhound')
INSERT INTO dog (breed) VALUES ('Cardigan Corgi')
INSERT INTO dog (breed) VALUES ('Cotondetulear')
INSERT INTO dog (breed) VALUES ('Dachshund')
INSERT INTO dog (breed) VALUES ('Dalmatian')
INSERT INTO dog (breed) VALUES ('Great Dane')
INSERT INTO dog (breed) VALUES ('Scottish Deerhound')
INSERT INTO dog (breed) VALUES ('Dhole')
INSERT INTO dog (breed) VALUES ('Dingo')
INSERT INTO dog (breed) VALUES ('Doberman')
INSERT INTO dog (breed) VALUES ('Norwegian Elkhound')
INSERT INTO dog (breed) VALUES ('Entlebucher')
INSERT INTO dog (breed) VALUES ('Eskimo')
INSERT INTO dog (breed) VALUES ('Lapphund Finnish')
INSERT INTO dog (breed) VALUES ('Bichon Frise')
INSERT INTO dog (breed) VALUES ('Germanshepherd')
INSERT INTO dog (breed) VALUES ('Italian Greyhound')
INSERT INTO dog (breed) VALUES ('Groenendael')
INSERT INTO dog (breed) VALUES ('Havanese')
INSERT INTO dog (breed) VALUES ('Afghan Hound')
INSERT INTO dog (breed) VALUES ('Basset Hound')
INSERT INTO dog (breed) VALUES ('Blood Hound')
INSERT INTO dog (breed) VALUES ('English Hound')
INSERT INTO dog (breed) VALUES ('Ibizan Hound')
INSERT INTO dog (breed) VALUES ('Plott Hound')
INSERT INTO dog (breed) VALUES ('Walker Hound')
INSERT INTO dog (breed) VALUES ('Husky')
INSERT INTO dog (breed) VALUES ('Keeshond')
INSERT INTO dog (breed) VALUES ('Kelpie')
INSERT INTO dog (breed) VALUES ('Komondor')
INSERT INTO dog (breed) VALUES ('Kuvasz')
INSERT INTO dog (breed) VALUES ('Labradoodle')
INSERT INTO dog (breed) VALUES ('Labrador')
INSERT INTO dog (breed) VALUES ('Leonberg')
INSERT INTO dog (breed) VALUES ('Lhasa')
INSERT INTO dog (breed) VALUES ('Malamute')
INSERT INTO dog (breed) VALUES ('Malinois')
INSERT INTO dog (breed) VALUES ('Maltese')
INSERT INTO dog (breed) VALUES ('Bull Mastiff')
INSERT INTO dog (breed) VALUES ('English Mastiff')
INSERT INTO dog (breed) VALUES ('Tibetan Mastiff')
INSERT INTO dog (breed) VALUES ('Mexicanhairless')
INSERT INTO dog (breed) VALUES ('Mix')
INSERT INTO dog (breed) VALUES ('Bernese Mountain')
INSERT INTO dog (breed) VALUES ('Swiss Mountain')
INSERT INTO dog (breed) VALUES ('Newfoundland')
INSERT INTO dog (breed) VALUES ('Otterhound')
INSERT INTO dog (breed) VALUES ('Caucasian Ovcharka')
INSERT INTO dog (breed) VALUES ('Papillon')
INSERT INTO dog (breed) VALUES ('Pekinese')
INSERT INTO dog (breed) VALUES ('Pembroke')
INSERT INTO dog (breed) VALUES ('Miniature Pinscher')
INSERT INTO dog (breed) VALUES ('Pitbull')
INSERT INTO dog (breed) VALUES ('German Pointer')
INSERT INTO dog (breed) VALUES ('Germanlonghair Pointer')
INSERT INTO dog (breed) VALUES ('Pomeranian')
INSERT INTO dog (breed) VALUES ('Medium Poodle')
INSERT INTO dog (breed) VALUES ('Toy Poodle')
INSERT INTO dog (breed) VALUES ('Pug')
INSERT INTO dog (breed) VALUES ('Puggle')
INSERT INTO dog (breed) VALUES ('Pyrenees')
INSERT INTO dog (breed) VALUES ('Redbone')
INSERT INTO dog (breed) VALUES ('Chesapeake Retriever')
INSERT INTO dog (breed) VALUES ('Curly Retriever')
INSERT INTO dog (breed) VALUES ('Flatcoated Retriever')
INSERT INTO dog (breed) VALUES ('Golden Retriever')
INSERT INTO dog (breed) VALUES ('Rhodesian Ridgeback')
INSERT INTO dog (breed) VALUES ('Rottweiler')
INSERT INTO dog (breed) VALUES ('Saluki')
INSERT INTO dog (breed) VALUES ('Samoyed')
INSERT INTO dog (breed) VALUES ('Schipperke')
INSERT INTO dog (breed) VALUES ('Giant Schnauzer')
INSERT INTO dog (breed) VALUES ('Miniature Schnauzer')
INSERT INTO dog (breed) VALUES ('Italian Segugio')
INSERT INTO dog (breed) VALUES ('English Setter')
INSERT INTO dog (breed) VALUES ('Gordon Setter')
INSERT INTO dog (breed) VALUES ('Irish Setter')
INSERT INTO dog (breed) VALUES ('Sharpei')
INSERT INTO dog (breed) VALUES ('English Sheepdog')
INSERT INTO dog (breed) VALUES ('Shetland Sheepdog')
INSERT INTO dog (breed) VALUES ('Shiba')
INSERT INTO dog (breed) VALUES ('Shihtzu')
INSERT INTO dog (breed) VALUES ('Blenheim Spaniel')
INSERT INTO dog (breed) VALUES ('Brittany Spaniel')
INSERT INTO dog (breed) VALUES ('Cocker Spaniel')
INSERT INTO dog (breed) VALUES ('Irish Spaniel')
INSERT INTO dog (breed) VALUES ('Japanese Spaniel')
INSERT INTO dog (breed) VALUES ('Sussex Spaniel')
INSERT INTO dog (breed) VALUES ('Welsh Spaniel')
INSERT INTO dog (breed) VALUES ('Japanese Spitz')
INSERT INTO dog (breed) VALUES ('English Springer')
INSERT INTO dog (breed) VALUES ('Stbernard')
INSERT INTO dog (breed) VALUES ('American Terrier')
INSERT INTO dog (breed) VALUES ('Australian Terrier')
INSERT INTO dog (breed) VALUES ('Bedlington Terrier')
INSERT INTO dog (breed) VALUES ('Border Terrier')
INSERT INTO dog (breed) VALUES ('Cairn Terrier')
INSERT INTO dog (breed) VALUES ('Dandie Terrier')
INSERT INTO dog (breed) VALUES ('Fox Terrier')
INSERT INTO dog (breed) VALUES ('Irish Terrier')
INSERT INTO dog (breed) VALUES ('Kerryblue Terrier')
INSERT INTO dog (breed) VALUES ('Lakeland Terrier')
INSERT INTO dog (breed) VALUES ('Norfolk Terrier')
INSERT INTO dog (breed) VALUES ('Norwich Terrier')
INSERT INTO dog (breed) VALUES ('Patterdale Terrier')
INSERT INTO dog (breed) VALUES ('Russell Terrier')
INSERT INTO dog (breed) VALUES ('Scottish Terrier')
INSERT INTO dog (breed) VALUES ('Sealyham Terrier')
INSERT INTO dog (breed) VALUES ('Silky Terrier')
INSERT INTO dog (breed) VALUES ('Tibetan Terrier')
INSERT INTO dog (breed) VALUES ('Toy Terrier')
INSERT INTO dog (breed) VALUES ('Welsh Terrier')
INSERT INTO dog (breed) VALUES ('Westhighland Terrier')
INSERT INTO dog (breed) VALUES ('Wheaten Terrier')
INSERT INTO dog (breed) VALUES ('Yorkshire Terrier')
INSERT INTO dog (breed) VALUES ('Tervuren')
INSERT INTO dog (breed) VALUES ('Vizsla')
INSERT INTO dog (breed) VALUES ('Spanish Waterdog')
INSERT INTO dog (breed) VALUES ('Weimaraner')
INSERT INTO dog (breed) VALUES ('Whippet')
INSERT INTO dog (breed) VALUES ('Irish Wolfhound')
