CREATE TABLE cat (
    id int auto_increment,
    breed varchar(64) NOT NULL
);

CREATE TABLE dog (
    id int auto_increment,
    breed varchar(64) NOT NULL
);

INSERT INTO cat (breed) VALUES ('Abyssinian');
INSERT INTO cat (breed) VALUES ('Aegean');
INSERT INTO cat (breed) VALUES ('American Bobtail');
INSERT INTO cat (breed) VALUES ('American Curl');
INSERT INTO cat (breed) VALUES ('American Shorthair');
INSERT INTO cat (breed) VALUES ('American Wirehair');
INSERT INTO cat (breed) VALUES ('Arabian Mau');
INSERT INTO cat (breed) VALUES ('Australian Mist');
INSERT INTO cat (breed) VALUES ('Balinese');
INSERT INTO cat (breed) VALUES ('Bambino');
INSERT INTO cat (breed) VALUES ('Bengal');
INSERT INTO cat (breed) VALUES ('Birman');
INSERT INTO cat (breed) VALUES ('Bombay');
INSERT INTO cat (breed) VALUES ('British Longhair');
INSERT INTO cat (breed) VALUES ('British Shorthair');
INSERT INTO cat (breed) VALUES ('Burmese');
INSERT INTO cat (breed) VALUES ('Burmilla');
INSERT INTO cat (breed) VALUES ('California Spangled');
INSERT INTO cat (breed) VALUES ('Chantilly-Tiffany');
INSERT INTO cat (breed) VALUES ('Chausie');
INSERT INTO cat (breed) VALUES ('Cheetoh');
INSERT INTO cat (breed) VALUES ('Colorpoint Shorthair');
INSERT INTO cat (breed) VALUES ('Cornish Rex');
INSERT INTO cat (breed) VALUES ('Cymric');
INSERT INTO cat (breed) VALUES ('Cyprus');
INSERT INTO cat (breed) VALUES ('Devon Rex');
INSERT INTO cat (breed) VALUES ('Donskoy');
INSERT INTO cat (breed) VALUES ('Dragon Li');
INSERT INTO cat (breed) VALUES ('Egyptian Mau');
INSERT INTO cat (breed) VALUES ('European Burmese');
INSERT INTO cat (breed) VALUES ('Exotic Shorthair');
INSERT INTO cat (breed) VALUES ('Havana Brown');
INSERT INTO cat (breed) VALUES ('Himalayan');
INSERT INTO cat (breed) VALUES ('Japanese Bobtail');
INSERT INTO cat (breed) VALUES ('Javanese');
INSERT INTO cat (breed) VALUES ('Khao Manee');
INSERT INTO cat (breed) VALUES ('Korat');
INSERT INTO cat (breed) VALUES ('Kurilian');
INSERT INTO cat (breed) VALUES ('LaPerm');
INSERT INTO cat (breed) VALUES ('Maine Coon');
INSERT INTO cat (breed) VALUES ('Malayan');
INSERT INTO cat (breed) VALUES ('Manx');
INSERT INTO cat (breed) VALUES ('Munchkin');
INSERT INTO cat (breed) VALUES ('Nebelung');
INSERT INTO cat (breed) VALUES ('Norwegian Forest Cat');
INSERT INTO cat (breed) VALUES ('Ocicat');
INSERT INTO cat (breed) VALUES ('Oriental');
INSERT INTO cat (breed) VALUES ('Persian');
INSERT INTO cat (breed) VALUES ('Pixie-bob');
INSERT INTO cat (breed) VALUES ('Ragamuffin');
INSERT INTO cat (breed) VALUES ('Ragdoll');
INSERT INTO cat (breed) VALUES ('Russian Blue');
INSERT INTO cat (breed) VALUES ('Savannah');
INSERT INTO cat (breed) VALUES ('Scottish Fold');
INSERT INTO cat (breed) VALUES ('Selkirk Rex');
INSERT INTO cat (breed) VALUES ('Siamese');
INSERT INTO cat (breed) VALUES ('Siberian');
INSERT INTO cat (breed) VALUES ('Singapura');
INSERT INTO cat (breed) VALUES ('Snowshoe');
INSERT INTO cat (breed) VALUES ('Somali');
INSERT INTO cat (breed) VALUES ('Sphynx');
INSERT INTO cat (breed) VALUES ('Tonkinese');
INSERT INTO cat (breed) VALUES ('Toyger');
INSERT INTO cat (breed) VALUES ('Turkish Angora');
INSERT INTO cat (breed) VALUES ('Turkish Van');
INSERT INTO cat (breed) VALUES ('York Chocolate');

INSERT INTO dog (breed) VALUES ('Affenpinscher');
INSERT INTO dog (breed) VALUES ('African');
INSERT INTO dog (breed) VALUES ('Airedale');
INSERT INTO dog (breed) VALUES ('Akita');
INSERT INTO dog (breed) VALUES ('Appenzeller');
INSERT INTO dog (breed) VALUES ('Shepherd Australian');
INSERT INTO dog (breed) VALUES ('Basenji');
INSERT INTO dog (breed) VALUES ('Beagle');
INSERT INTO dog (breed) VALUES ('Bluetick');
INSERT INTO dog (breed) VALUES ('Borzoi');
INSERT INTO dog (breed) VALUES ('Bouvier');
INSERT INTO dog (breed) VALUES ('Boxer');
INSERT INTO dog (breed) VALUES ('Brabancon');
INSERT INTO dog (breed) VALUES ('Briard');
INSERT INTO dog (breed) VALUES ('Norwegian Buhund');
INSERT INTO dog (breed) VALUES ('Boston Bulldog');
INSERT INTO dog (breed) VALUES ('English Bulldog');
INSERT INTO dog (breed) VALUES ('French Bulldog');
INSERT INTO dog (breed) VALUES ('Staffordshire Bullterrier');
INSERT INTO dog (breed) VALUES ('Australian Cattledog');
INSERT INTO dog (breed) VALUES ('Chihuahua');
INSERT INTO dog (breed) VALUES ('Chow');
INSERT INTO dog (breed) VALUES ('Clumber');
INSERT INTO dog (breed) VALUES ('Cockapoo');
INSERT INTO dog (breed) VALUES ('Border Collie');
INSERT INTO dog (breed) VALUES ('Coonhound');
INSERT INTO dog (breed) VALUES ('Cardigan Corgi');
INSERT INTO dog (breed) VALUES ('Cotondetulear');
INSERT INTO dog (breed) VALUES ('Dachshund');
INSERT INTO dog (breed) VALUES ('Dalmatian');
INSERT INTO dog (breed) VALUES ('Great Dane');
INSERT INTO dog (breed) VALUES ('Scottish Deerhound');
INSERT INTO dog (breed) VALUES ('Dhole');
INSERT INTO dog (breed) VALUES ('Dingo');
INSERT INTO dog (breed) VALUES ('Doberman');
INSERT INTO dog (breed) VALUES ('Norwegian Elkhound');
INSERT INTO dog (breed) VALUES ('Entlebucher');
INSERT INTO dog (breed) VALUES ('Eskimo');
INSERT INTO dog (breed) VALUES ('Lapphund Finnish');
INSERT INTO dog (breed) VALUES ('Bichon Frise');
INSERT INTO dog (breed) VALUES ('Germanshepherd');
INSERT INTO dog (breed) VALUES ('Italian Greyhound');
INSERT INTO dog (breed) VALUES ('Groenendael');
INSERT INTO dog (breed) VALUES ('Havanese');
INSERT INTO dog (breed) VALUES ('Afghan Hound');
INSERT INTO dog (breed) VALUES ('Basset Hound');
INSERT INTO dog (breed) VALUES ('Blood Hound');
INSERT INTO dog (breed) VALUES ('English Hound');
INSERT INTO dog (breed) VALUES ('Ibizan Hound');
INSERT INTO dog (breed) VALUES ('Plott Hound');
INSERT INTO dog (breed) VALUES ('Walker Hound');
INSERT INTO dog (breed) VALUES ('Husky');
INSERT INTO dog (breed) VALUES ('Keeshond');
INSERT INTO dog (breed) VALUES ('Kelpie');
INSERT INTO dog (breed) VALUES ('Komondor');
INSERT INTO dog (breed) VALUES ('Kuvasz');
INSERT INTO dog (breed) VALUES ('Labradoodle');
INSERT INTO dog (breed) VALUES ('Labrador');
INSERT INTO dog (breed) VALUES ('Leonberg');
INSERT INTO dog (breed) VALUES ('Lhasa');
INSERT INTO dog (breed) VALUES ('Malamute');
INSERT INTO dog (breed) VALUES ('Malinois');
INSERT INTO dog (breed) VALUES ('Maltese');
INSERT INTO dog (breed) VALUES ('Bull Mastiff');
INSERT INTO dog (breed) VALUES ('English Mastiff');
INSERT INTO dog (breed) VALUES ('Tibetan Mastiff');
INSERT INTO dog (breed) VALUES ('Mexicanhairless');
INSERT INTO dog (breed) VALUES ('Mix');
INSERT INTO dog (breed) VALUES ('Bernese Mountain');
INSERT INTO dog (breed) VALUES ('Swiss Mountain');
INSERT INTO dog (breed) VALUES ('Newfoundland');
INSERT INTO dog (breed) VALUES ('Otterhound');
INSERT INTO dog (breed) VALUES ('Caucasian Ovcharka');
INSERT INTO dog (breed) VALUES ('Papillon');
INSERT INTO dog (breed) VALUES ('Pekinese');
INSERT INTO dog (breed) VALUES ('Pembroke');
INSERT INTO dog (breed) VALUES ('Miniature Pinscher');
INSERT INTO dog (breed) VALUES ('Pitbull');
INSERT INTO dog (breed) VALUES ('German Pointer');
INSERT INTO dog (breed) VALUES ('Germanlonghair Pointer');
INSERT INTO dog (breed) VALUES ('Pomeranian');
INSERT INTO dog (breed) VALUES ('Medium Poodle');
INSERT INTO dog (breed) VALUES ('Toy Poodle');
INSERT INTO dog (breed) VALUES ('Pug');
INSERT INTO dog (breed) VALUES ('Puggle');
INSERT INTO dog (breed) VALUES ('Pyrenees');
INSERT INTO dog (breed) VALUES ('Redbone');
INSERT INTO dog (breed) VALUES ('Chesapeake Retriever');
INSERT INTO dog (breed) VALUES ('Curly Retriever');
INSERT INTO dog (breed) VALUES ('Flatcoated Retriever');
INSERT INTO dog (breed) VALUES ('Golden Retriever');
INSERT INTO dog (breed) VALUES ('Rhodesian Ridgeback');
INSERT INTO dog (breed) VALUES ('Rottweiler');
INSERT INTO dog (breed) VALUES ('Saluki');
INSERT INTO dog (breed) VALUES ('Samoyed');
INSERT INTO dog (breed) VALUES ('Schipperke');
INSERT INTO dog (breed) VALUES ('Giant Schnauzer');
INSERT INTO dog (breed) VALUES ('Miniature Schnauzer');
INSERT INTO dog (breed) VALUES ('Italian Segugio');
INSERT INTO dog (breed) VALUES ('English Setter');
INSERT INTO dog (breed) VALUES ('Gordon Setter');
INSERT INTO dog (breed) VALUES ('Irish Setter');
INSERT INTO dog (breed) VALUES ('Sharpei');
INSERT INTO dog (breed) VALUES ('English Sheepdog');
INSERT INTO dog (breed) VALUES ('Shetland Sheepdog');
INSERT INTO dog (breed) VALUES ('Shiba');
INSERT INTO dog (breed) VALUES ('Shihtzu');
INSERT INTO dog (breed) VALUES ('Blenheim Spaniel');
INSERT INTO dog (breed) VALUES ('Brittany Spaniel');
INSERT INTO dog (breed) VALUES ('Cocker Spaniel');
INSERT INTO dog (breed) VALUES ('Irish Spaniel');
INSERT INTO dog (breed) VALUES ('Japanese Spaniel');
INSERT INTO dog (breed) VALUES ('Sussex Spaniel');
INSERT INTO dog (breed) VALUES ('Welsh Spaniel');
INSERT INTO dog (breed) VALUES ('Japanese Spitz');
INSERT INTO dog (breed) VALUES ('English Springer');
INSERT INTO dog (breed) VALUES ('Stbernard');
INSERT INTO dog (breed) VALUES ('American Terrier');
INSERT INTO dog (breed) VALUES ('Australian Terrier');
INSERT INTO dog (breed) VALUES ('Bedlington Terrier');
INSERT INTO dog (breed) VALUES ('Border Terrier');
INSERT INTO dog (breed) VALUES ('Cairn Terrier');
INSERT INTO dog (breed) VALUES ('Dandie Terrier');
INSERT INTO dog (breed) VALUES ('Fox Terrier');
INSERT INTO dog (breed) VALUES ('Irish Terrier');
INSERT INTO dog (breed) VALUES ('Kerryblue Terrier');
INSERT INTO dog (breed) VALUES ('Lakeland Terrier');
INSERT INTO dog (breed) VALUES ('Norfolk Terrier');
INSERT INTO dog (breed) VALUES ('Norwich Terrier');
INSERT INTO dog (breed) VALUES ('Patterdale Terrier');
INSERT INTO dog (breed) VALUES ('Russell Terrier');
INSERT INTO dog (breed) VALUES ('Scottish Terrier');
INSERT INTO dog (breed) VALUES ('Sealyham Terrier');
INSERT INTO dog (breed) VALUES ('Silky Terrier');
INSERT INTO dog (breed) VALUES ('Tibetan Terrier');
INSERT INTO dog (breed) VALUES ('Toy Terrier');
INSERT INTO dog (breed) VALUES ('Welsh Terrier');
INSERT INTO dog (breed) VALUES ('Westhighland Terrier');
INSERT INTO dog (breed) VALUES ('Wheaten Terrier');
INSERT INTO dog (breed) VALUES ('Yorkshire Terrier');
INSERT INTO dog (breed) VALUES ('Tervuren');
INSERT INTO dog (breed) VALUES ('Vizsla');
INSERT INTO dog (breed) VALUES ('Spanish Waterdog');
INSERT INTO dog (breed) VALUES ('Weimaraner');
INSERT INTO dog (breed) VALUES ('Whippet');
INSERT INTO dog (breed) VALUES ('Irish Wolfhound');
